using System.Globalization;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace CiscoConfigGuiWpf;

public static class LocalizationService
{
    private static string _language = "de-DE";

    public static string CurrentLanguage => _language;
    public static bool IsEnglish => _language.StartsWith("en", StringComparison.OrdinalIgnoreCase);

    public static void SetLanguage(string? language)
    {
        var requested = (language ?? "system").Trim();
        if (requested.Equals("system", StringComparison.OrdinalIgnoreCase))
            requested = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("en", StringComparison.OrdinalIgnoreCase) ? "en-US" : "de-DE";
        _language = requested.StartsWith("en", StringComparison.OrdinalIgnoreCase) ? "en-US" : "de-DE";
        try
        {
            var culture = CultureInfo.GetCultureInfo(_language);
            CultureInfo.CurrentUICulture = culture;
            CultureInfo.CurrentCulture = culture;
        }
        catch
        {
            _language = "de-DE";
        }
    }

    public static string TranslateText(string? text) => TranslateText(text, _language);

    public static string TranslateText(string? text, string? targetLanguage)
    {
        var value = text ?? string.Empty;
        var english = (targetLanguage ?? string.Empty).StartsWith("en", StringComparison.OrdinalIgnoreCase);
        if (!english || string.IsNullOrWhiteSpace(value)) return value;

        if (Exact.TryGetValue(value, out var exact)) return exact;

        // Navigationssymbole beibehalten, sichtbaren Text dahinter übersetzen.
        var iconMatch = Regex.Match(value, @"^(?<icon>[^\p{L}\p{N}]{1,4}\s{1,3})(?<text>.+)$");
        if (iconMatch.Success)
            return iconMatch.Groups["icon"].Value + TranslateText(iconMatch.Groups["text"].Value, targetLanguage);

        var result = value;
        foreach (var replacement in PhraseReplacements)
            result = ReplaceOrdinalIgnoreCase(result, replacement.Key, replacement.Value);

        foreach (var replacement in WordReplacements)
            result = Regex.Replace(result, $@"\b{Regex.Escape(replacement.Key)}\b", replacement.Value, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        return result;
    }

    public static DataTemplate CreateLocalizedStringTemplate()
    {
#pragma warning disable CS0618
        var factory = new FrameworkElementFactory(typeof(TextBlock));
#pragma warning restore CS0618
        factory.SetValue(TextBlock.TextTrimmingProperty, TextTrimming.CharacterEllipsis);
        factory.SetValue(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center);
        factory.SetBinding(TextBlock.TextProperty, new Binding { Converter = new LocalizedTextConverter() });
        return new DataTemplate { VisualTree = factory };
    }

    private static string ReplaceOrdinalIgnoreCase(string input, string oldValue, string newValue)
    {
        if (string.IsNullOrEmpty(oldValue)) return input;
        return Regex.Replace(input, Regex.Escape(oldValue), _ => newValue, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    }

    private static readonly Dictionary<string, string> Exact = new(StringComparer.Ordinal)
    {
        ["Cisco Konfigurator"] = "Cisco Configurator",
        ["IOS / IOS-XE Konfiguration strukturiert erstellen und prüfen"] = "Create and validate IOS / IOS-XE configurations in a structured workflow",
        ["Gerät"] = "Device",
        ["Modus"] = "Mode",
        ["Alles zurücksetzen"] = "Reset all",
        ["Vorlage laden"] = "Load template",
        ["Vorlage sichern"] = "Save template",
        ["TXT Export"] = "TXT export",
        ["Kopieren"] = "Copy",
        ["Übersicht"] = "Overview",
        ["Basis"] = "Base configuration",
        ["Management"] = "Management",
        ["Management & Zugriff"] = "Management & access",
        ["Interfaces"] = "Interfaces",
        ["Interfaces & Ports"] = "Interfaces & ports",
        ["Switching"] = "Switching",
        ["Routing"] = "Routing",
        ["IPv6/DHCP/ACL"] = "IPv6 / DHCP / ACL",
        ["Netzdienste"] = "Network services",
        ["Security/WAN"] = "Security / WAN",
        ["Sicherheit & WAN"] = "Security & WAN",
        ["Gegenstelle"] = "Peer device",
        ["Import"] = "Import",
        ["Betrieb"] = "Operations",
        ["Ausgabe"] = "Output",
        ["Projekt"] = "Project",
        ["IPAM / Ports"] = "IPAM / ports",
        ["Subnetting"] = "Subnetting",
        ["Analyse"] = "Analysis",
        ["Befehlsregister"] = "Command registry",
        ["Diagramm / Bericht"] = "Diagram / report",
        ["Einstellungen"] = "Settings",
        ["KONFIGURATION"] = "CONFIGURATION",
        ["WERKZEUGE"] = "TOOLS",
        ["DOKUMENTATION"] = "DOCUMENTATION",
        ["SYSTEM"] = "SYSTEM",
        ["Konfigurationsübersicht"] = "Configuration overview",
        ["Zielgerät"] = "Target device",
        ["Aktive Module"] = "Active modules",
        ["Validierung"] = "Validation",
        ["Bereit"] = "Ready",
        ["Empfohlener Ablauf"] = "Recommended workflow",
        ["Ziel festlegen"] = "Select target",
        ["Module aktivieren"] = "Enable modules",
        ["Werte prüfen"] = "Validate values",
        ["Ausgeben"] = "Generate output",
        ["Direktzugriff"] = "Quick access",
        ["Spanning Tree"] = "Spanning Tree",
        ["Modulübersicht"] = "Module overview",
        ["Module durchsuchen"] = "Search modules",
        ["Alle"] = "All",
        ["Keine"] = "None",
        ["Favoriten"] = "Favorites",
        ["Felder"] = "fields",
        ["Aus"] = "Off",
        ["An"] = "On",
        ["Ja"] = "Yes",
        ["Nein"] = "No",
        ["Ohne VRF"] = "Without VRF",
        ["Mit VRF"] = "With VRF",
        ["Router"] = "Router",
        ["L3-Switch"] = "Layer 3 switch",
        ["L2-Switch"] = "Layer 2 switch",
        ["Deutsch"] = "German",
        ["English"] = "English",
        ["Systemsprache"] = "System language",
        ["Dunkel"] = "Dark",
        ["Hell"] = "Light",
        ["System"] = "System",
        ["Orange"] = "Orange",
        ["Blau"] = "Blue",
        ["Grün"] = "Green",
        ["Violett"] = "Purple",
        ["Klein"] = "Small",
        ["Normal"] = "Normal",
        ["Groß"] = "Large",
        ["Hochformat"] = "Portrait",
        ["Querformat"] = "Landscape",
        ["Streng"] = "Strict",
        ["Tolerant"] = "Tolerant",
        ["Nur vorschlagen"] = "Suggest only",
        ["Automatisch anwenden"] = "Apply automatically",
        ["Dual Stack"] = "Dual stack",
        ["Nur IPv4"] = "IPv4 only",
        ["Nur IPv6"] = "IPv6 only",
        ["Allgemein"] = "General",
        ["Sprache"] = "Language",
        ["Darstellung"] = "Appearance",
        ["Konfiguration"] = "Configuration",
        ["Import / Export"] = "Import / export",
        ["Projekte / Sicherung"] = "Projects / backup",
        ["SSH / Betrieb"] = "SSH / operations",
        ["Erweitert"] = "Advanced",
        ["Übernehmen"] = "Apply",
        ["Speichern"] = "Save",
        ["Schließen"] = "Close",
        ["Standardwerte"] = "Defaults",
        ["Einstellungen exportieren"] = "Export settings",
        ["Einstellungen importieren"] = "Import settings",
        ["Anwendungssprache"] = "Application language",
        ["Berichtssprache"] = "Report language",
        ["Startseite"] = "Start page",
        ["Letztes Projekt automatisch laden"] = "Load last project automatically",
        ["Zurücksetzen bestätigen"] = "Confirm reset",
        ["Design"] = "Theme",
        ["Akzentfarbe"] = "Accent color",
        ["Schriftgröße"] = "Font size",
        ["Kompakte Ansicht"] = "Compact view",
        ["Animationen aktivieren"] = "Enable animations",
        ["Tooltips aktivieren"] = "Enable tooltips",
        ["Live-Vorschau anzeigen"] = "Show live preview",
        ["Navigation einklappbar"] = "Collapsible navigation",
        ["Standardgerät"] = "Default device",
        ["Standardmodus"] = "Default mode",
        ["Standardplattform"] = "Default platform",
        ["Standard-Interface"] = "Default interface",
        ["Standard-IP-Stack"] = "Default IP stack",
        ["Kommentare erzeugen"] = "Generate comments",
        ["Abschnittstrenner erzeugen"] = "Generate section separators",
        ["enable exportieren"] = "Export enable",
        ["configure terminal exportieren"] = "Export configure terminal",
        ["end exportieren"] = "Export end",
        ["write memory exportieren"] = "Export write memory",
        ["Validierungsmodus"] = "Validation mode",
        ["Automatische Korrekturen"] = "Automatic fixes",
        ["Standard-Exportordner"] = "Default export folder",
        ["Dateinamensmuster"] = "File name pattern",
        ["Zeilenenden"] = "Line endings",
        ["Nach Modulen sortieren"] = "Sort by modules",
        ["Unbekannte Befehle übernehmen"] = "Keep unknown commands",
        ["Zusatzbefehle übernehmen"] = "Include custom commands",
        ["Zeitstempel im Dateinamen"] = "Timestamp in file name",
        ["Gegenstellenkonfiguration mitexportieren"] = "Export peer configuration",
        ["Rollback-Datei erzeugen"] = "Generate rollback file",
        ["Berichte gemeinsam exportieren"] = "Export reports together",
        ["Autosave aktivieren"] = "Enable autosave",
        ["Autosave-Intervall (Sekunden)"] = "Autosave interval (seconds)",
        ["Anzahl lokaler Sicherungen"] = "Number of local backups",
        ["Backup-Ordner"] = "Backup folder",
        ["Projekt beim Beenden speichern"] = "Save project on exit",
        ["Nach Absturz wiederherstellen"] = "Restore after crash",
        ["Konfigurationshistorie aktivieren"] = "Enable configuration history",
        ["Maximale Historieneinträge"] = "Maximum history entries",
        ["Standard-SSH-Port"] = "Default SSH port",
        ["Verbindungs-Timeout (Sekunden)"] = "Connection timeout (seconds)",
        ["Befehls-Timeout (Sekunden)"] = "Command timeout (seconds)",
        ["Zeilenverzögerung (ms)"] = "Line delay (ms)",
        ["Vor Übertragung sichern"] = "Back up before transfer",
        ["Bei Fehler abbrechen"] = "Abort on error",
        ["Befehle vor dem Senden anzeigen"] = "Show commands before sending",
        ["Passwörter speichern"] = "Store passwords",
        ["Sitzungsprotokoll aktivieren"] = "Enable session logging",
        ["Geräte-Backup-Ordner"] = "Device backup folder",
        ["Automatische Diagrammanordnung"] = "Automatic diagram layout",
        ["Am Raster ausrichten"] = "Snap to grid",
        ["Verbindungstypen anzeigen"] = "Show connection types",
        ["Interface-Namen anzeigen"] = "Show interface names",
        ["IP-Adressen anzeigen"] = "Show IP addresses",
        ["VLANs anzeigen"] = "Show VLANs",
        ["Standard-Berichtsformat"] = "Default report format",
        ["Firmenname"] = "Company name",
        ["Projektverantwortlicher"] = "Project manager",
        ["Berichtslogo"] = "Report logo",
        ["Seitenformat"] = "Page size",
        ["Ausrichtung"] = "Orientation",
        ["Strenge Importprüfung"] = "Strict import validation",
        ["Entwicklermodus"] = "Developer mode",
        ["Diagnosedetails aufnehmen"] = "Include diagnostic details",
        ["Konfiguration erzeugen"] = "Generate configuration",
        ["Vorschau aktualisieren"] = "Refresh preview",
        ["Vorschau kopieren"] = "Copy preview",
        ["Gegenstelle anzeigen"] = "Show peer device",
        ["COM / Konsole"] = "COM / console",
        ["COM-Port wählen"] = "Select COM port",
        ["COM-Testmodus aktivieren"] = "Enable COM test mode",
        ["Konfiguration senden"] = "Send configuration",
        ["Netzwerkdiagramm"] = "Network diagram",
        ["Interaktives Netzwerkdiagramm"] = "Interactive network diagram",
        ["Quelle"] = "Source",
        ["Ziel"] = "Target",
        ["Typ"] = "Type",
        ["Bezeichnung"] = "Description",
        ["Verbindung hinzufügen"] = "Add connection",
        ["Letzte entfernen"] = "Remove last",
        ["Aktualisieren"] = "Refresh",
        ["Automatisch anordnen"] = "Automatic layout",
        ["SVG Export"] = "SVG export",
        ["Berichtsexport"] = "Report export",
        ["Projektbericht"] = "Project report",
        ["HTML Export"] = "HTML export",
        ["DOCX Export"] = "DOCX export",
        ["PDF Export"] = "PDF export",
        ["Mehrgeräte-Projekt"] = "Multi-device project",
        ["Projektinformationen"] = "Project information",
        ["Projektname"] = "Project name",
        ["Beschreibung"] = "Description",
        ["Neu"] = "New",
        ["Öffnen"] = "Open",
        ["Verbindung testen"] = "Test connection",
        ["Running sichern"] = "Back up running config",
        ["Startup sichern"] = "Back up startup config",
        ["Backup exportieren"] = "Export backup",
        ["Backup als Alt vergleichen"] = "Use backup as old configuration",
        ["Backup entfernen"] = "Remove backup",
        ["Zeit"] = "Time",
        ["Warnung"] = "Warning",
        ["Fehler"] = "Error",
        ["Hinweis"] = "Notice",
        ["Keine Warnungen"] = "No warnings",
        ["Validierungswarnungen"] = "Validation warnings",
        ["Duplikate erkannt"] = "Duplicates detected",
        ["Kopiert"] = "Copied",
        ["Export abgeschlossen"] = "Export completed",
        ["Cisco-Konfiguration speichern"] = "Save Cisco configuration",
        ["Textdatei (*.txt)"] = "Text file (*.txt)",
        ["Alle Dateien (*.*)"] = "All files (*.*)",
        ["Windows (CRLF)"] = "Windows (CRLF)",
        ["Unix (LF)"] = "Unix (LF)",
        ["Netzwerkprojekt speichern"] = "Save network project",
        ["Netzwerkdiagramm exportieren"] = "Export network diagram",
        ["Projektbericht exportieren"] = "Export project report",
        ["Berichtsvorschau"] = "Report preview",
        ["SSH-Ausgabe"] = "SSH output",
        ["Entwurf"] = "Draft",
        ["Konfiguration vorhanden"] = "Configuration available",
        ["Grunddaten"] = "General settings",
        ["Benutzer / Rechte"] = "Users / privileges",
        ["Einzelinterfaces"] = "Individual interfaces",
        ["Interface-Ranges"] = "Interface ranges",
        ["Router-on-a-Stick Assistent"] = "Router-on-a-Stick assistant",
        ["QoS Basic"] = "Basic QoS",
        ["Interface-Profile"] = "Interface profiles",
        ["Trunk / Uplink"] = "Trunk / uplink",
        ["Interface-Rollenmodell"] = "Interface role model",
        ["VLANs und SVIs"] = "VLANs and SVIs",
        ["Switch Security"] = "Switch security",
        ["Access-Switch"] = "Access switch",
        ["Spanning Tree (dynamisch)"] = "Spanning Tree (dynamic)",
        ["VLAN-/IP-Plan"] = "VLAN / IP plan",
        ["Routing allgemein"] = "General routing",
        ["Statische Routen"] = "Static routes",
        ["Route-Maps / Prefix-Lists"] = "Route maps / prefix lists",
        ["OSPF Optionen"] = "OSPF options",
        ["BGP Optionen"] = "BGP options",
        ["VRF Definitionen"] = "VRF definitions",
        ["VLAN / SVI VRF"] = "VLAN / SVI VRF",
        ["Static Routes VRF"] = "Static routes VRF",
        ["IPv6 Zusatz"] = "Additional IPv6 settings",
        ["IPv6 Routingprotokolle"] = "IPv6 routing protocols",
        ["ACL-Assistent"] = "ACL assistant",
        ["Eigene Zusatzbefehle"] = "Custom commands",
        ["WAN-Failover-Assistent"] = "WAN failover assistant",
        ["DMZ-Assistent"] = "DMZ assistant",
        ["Zone-Based Firewall"] = "Zone-based firewall",
        ["VPN Site-to-Site IPsec"] = "Site-to-site IPsec VPN",
        ["Zeitzone"] = "Time zone",
        ["UTC-Abweichung Stunden"] = "UTC offset hours",
        ["UTC-Abweichung Minuten"] = "UTC offset minutes",
        ["Sommerzeit-Name"] = "Daylight saving time name",
        ["Sommerzeit-Regel"] = "Daylight saving time rule",
        ["Standort"] = "Location",
        ["VTY Ende"] = "VTY end",
        ["Buffered Größe"] = "Buffered size",
        ["AAA Radius nutzen"] = "Use AAA RADIUS",
        ["Native VLAN optional"] = "Native VLAN optional",
        ["Intervall Sekunden"] = "Interval in seconds",
        ["Strikte Kompatibilität"] = "Strict compatibility",
        ["System-ID erweitern"] = "Extend system ID",
        ["Path-Cost-Methode"] = "Path cost method",
        ["Root-Rolle"] = "Root role",
        ["Bridge-Priorität"] = "Bridge priority",
        ["MST Root-Rolle"] = "MST root role",
        ["MST Bridge-Priorität"] = "MST bridge priority",
        ["Errdisable-Intervall Sekunden"] = "Errdisable interval in seconds",
        ["Rücksetzen: Scope|Target|Parameter"] = "Reset: scope|target|parameter",
        ["ACL-Name"] = "ACL name",
        ["Aktion"] = "Action",
        ["Protokoll"] = "Protocol",
        ["Richtung"] = "Direction",
        ["Ein Cisco-Befehl pro Zeile"] = "One Cisco command per line",
        ["Bitte zuerst ein Projektgerät auswählen."] = "Select a project device first.",
        ["Der Gegenstellenentwurf wurde als Projektgerät angelegt. Platzhalter <...> müssen vor einer Übertragung geprüft werden."] = "The peer draft was added as a project device. Placeholders <...> must be reviewed before transfer.",
        ["Für dieses Projektgerät ist noch keine Konfiguration gespeichert."] = "No configuration has been stored for this project device yet.",
        ["Aktuelles Projekt verwerfen und ein neues Projekt beginnen?"] = "Discard the current project and start a new project?",
        ["Neues Projekt"] = "New project",
        ["Projekt konnte nicht geöffnet werden"] = "Project could not be opened",
        ["Projekt wurde gespeichert."] = "Project was saved.",
        ["Speicherfehler"] = "Save error",
        ["Korrekturen wurden angewendet. Platzhalter und sicherheitsrelevante Werte müssen geprüft werden."] = "Fixes were applied. Placeholders and security-relevant values must be reviewed.",
        ["Auto-Korrektur"] = "Automatic correction",
        ["Host und Benutzer müssen angegeben werden."] = "Host and username are required.",
        ["SSH-Übertragung"] = "SSH transfer",
        ["Übertragung abgeschlossen."] = "Transfer completed.",
        ["Übertragung fehlgeschlagen. Ausgabe prüfen."] = "Transfer failed. Check the output.",
        ["Quelle und Ziel müssen ausgewählt werden."] = "Source and target must be selected.",
        ["Quelle und Ziel dürfen nicht identisch sein."] = "Source and target must not be identical.",
        ["Diese Verbindung ist bereits im Projekt vorhanden."] = "This connection already exists in the project.",
        ["Bericht wurde exportiert."] = "Report was exported.",
        ["Exportfehler"] = "Export error",
        ["Vorschau wurde in die Zwischenablage kopiert."] = "Preview was copied to the clipboard.",
        ["Gegenstellenanforderungen wurden kopiert."] = "Peer requirements were copied.",
        ["COM abgeschlossen"] = "COM completed",
        ["COM-Fehler"] = "COM error",
        ["Konfiguration wurde über den gewählten COM-Port gesendet."] = "Configuration was sent through the selected COM port.",
        ["Es wurde ein Autosave gefunden. Wiederherstellen?"] = "An autosave was found. Restore it?",
    };

    private static readonly KeyValuePair<string, string>[] PhraseReplacements =
    {
        new("Gerät auswählen, benötigte Module aktivieren, Eingaben prüfen und die fertige Cisco-Konfiguration ausgeben.", "Select a device, enable required modules, validate the input and generate the final Cisco configuration."),
        new("Wird über die Kopfzeile ausgewählt.", "Selected in the top bar."),
        new("Nur aktive Module werden exportiert.", "Only active modules are exported."),
        new("Warnungen führen direkt zum betroffenen Feld.", "Warnings navigate directly to the affected field."),
        new("Häufig verwendete Bereiche ohne Umweg öffnen.", "Open frequently used areas directly."),
        new("Durchsucht die Module dieses Bereichs.", "Searches the modules in this section."),
        new("Aktiviert alle sichtbaren Module.", "Enables all visible modules."),
        new("Deaktiviert alle Module dieses Bereichs.", "Disables all modules in this section."),
        new("Aktiviert nur die markierten Favoritenmodule.", "Enables only favorite modules."),
        new("Als Favorit markieren oder entfernen.", "Add to or remove from favorites."),
        new("Modul aktivieren", "Enable module"),
        new("keine offensichtlichen Pflichtfeld-Warnungen", "no obvious required-field warnings"),
        new("Module aktiv", "modules active"),
        new("von", "of"),
        new("Klicke auf die Statuszeile, um zur ersten Warnung zu springen.", "Click the status bar to navigate to the first warning."),
        new("Für die aktuell aktivierten Module wurden keine offensichtlichen leeren Pflichtfelder erkannt.", "No obvious empty required fields were detected for the currently active modules."),
        new("Setzt alle Eingaben und Module auf die Ausgangswerte zurück.", "Resets all inputs and modules to their default state."),
        new("Lädt eine gespeicherte JSON-Vorlage.", "Loads a saved JSON template."),
        new("Speichert Eingaben und aktive Module als JSON-Vorlage.", "Saves inputs and active modules as a JSON template."),
        new("Erzeugt die Konfiguration und speichert sie als Textdatei.", "Generates the configuration and saves it as a text file."),
        new("Erzeugt die Konfiguration und kopiert sie in die Zwischenablage.", "Generates the configuration and copies it to the clipboard."),
        new("Verwaltet mehrere Router und Switches mit gemeinsamen IPAM-, Link-, Backup- und Berichtsdaten.", "Manages multiple routers and switches with shared IPAM, link, backup and report data."),
        new("Geräte können mit der Maus verschoben werden.", "Devices can be moved with the mouse."),
        new("Geräte per Drag & Drop verschieben", "Move devices by drag and drop"),
        new("Verbindungstypen", "connection types"),
        new("Erzeugt Geräteübersicht, IP-Plan, Verbindungen, Prüfungen und Testplan", "Generates device overview, IP plan, connections, checks and test plan"),
        new("Konfiguration wurde in die Zwischenablage kopiert.", "Configuration was copied to the clipboard."),
        new("Konfiguration wurde gespeichert.", "Configuration was saved."),
        new("Fehler beim Erzeugen", "Generation error"),
        new("Fehler beim Export", "Export error"),
        new("Eingaben wurden geändert.", "Inputs were changed."),
        new("Klicke auf", "Click"),
        new("um die", "to"),
        new("anzuzeigen", "display"),
        new("wiederherstellen", "restore"),
        new("gefunden", "found"),
        new("Einstellungen wurden gespeichert.", "Settings were saved."),
        new("Einstellungen wurden importiert.", "Settings were imported."),
        new("Einstellungen wurden exportiert.", "Settings were exported."),
        new("Alle Einstellungen auf Standardwerte zurücksetzen?", "Reset all settings to defaults?"),
        new("Die Sprache wird ohne Neustart umgeschaltet.", "The language is switched without restarting."),
        new("Cisco-Befehle und interne Konfigurationswerte werden nicht übersetzt.", "Cisco commands and internal configuration values are not translated."),
        new("Passwörter werden standardmäßig nicht gespeichert.", "Passwords are not stored by default."),
        new("Änderungen übernehmen", "Apply changes"),
        new("Einstellungen verwalten", "Manage settings")
    };

    private static readonly Dictionary<string, string> WordReplacements = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Geräte"] = "devices",
        ["Gerät"] = "device",
        ["Module"] = "modules",
        ["Modul"] = "module",
        ["Feld"] = "field",
        ["Felder"] = "fields",
        ["aktiv"] = "active",
        ["inaktiv"] = "inactive",
        ["anzeigen"] = "show",
        ["ausblenden"] = "hide",
        ["speichern"] = "save",
        ["laden"] = "load",
        ["löschen"] = "delete",
        ["entfernen"] = "remove",
        ["hinzufügen"] = "add",
        ["prüfen"] = "validate",
        ["erzeugen"] = "generate",
        ["exportieren"] = "export",
        ["importieren"] = "import",
        ["auswählen"] = "select",
        ["aktivieren"] = "enable",
        ["deaktivieren"] = "disable",
        ["Standard"] = "default",
        ["optional"] = "optional",
        ["Pflichtfeld"] = "required field",
        ["Warnungen"] = "warnings",
        ["Warnung"] = "warning",
        ["Fehler"] = "error",
        ["Hinweise"] = "notices",
        ["Hinweis"] = "notice",
        ["Beschreibung"] = "description",
        ["Name"] = "name",
        ["Adresse"] = "address",
        ["Netz"] = "network",
        ["Schnittstelle"] = "interface",
        ["Verbindung"] = "connection",
        ["Verbindungen"] = "connections",
        ["Konfiguration"] = "configuration",
        ["Bericht"] = "report",
        ["Diagramm"] = "diagram",
        ["Projekt"] = "project",
        ["Sicherung"] = "backup",
        ["Betrieb"] = "operations",
        ["Ausgabe"] = "output",
        ["Zugriff"] = "access",
        ["Benutzer"] = "user",
        ["Passwort"] = "password",
        ["Zeit"] = "time",
        ["Quelle"] = "source",
        ["Ziel"] = "target",
        ["Bereich"] = "section",
        ["Übersicht"] = "overview",
        ["Einstellungen"] = "settings",
        ["Zeitzone"] = "time zone",
        ["Abweichung"] = "offset",
        ["Stunden"] = "hours",
        ["Minuten"] = "minutes",
        ["Sommerzeit"] = "daylight saving time",
        ["Regel"] = "rule",
        ["Standort"] = "location",
        ["Ende"] = "end",
        ["Größe"] = "size",
        ["nutzen"] = "use",
        ["Rechte"] = "privileges",
        ["Assistent"] = "assistant",
        ["Profil"] = "profile",
        ["Profile"] = "profiles",
        ["Rolle"] = "role",
        ["Rollen"] = "roles",
        ["Wert"] = "value",
        ["Mehrere"] = "multiple",
        ["Rücksetzen"] = "reset",
        ["allgemein"] = "general",
        ["Statische"] = "static",
        ["Routen"] = "routes",
        ["Optionen"] = "options",
        ["Definitionen"] = "definitions",
        ["Zusatz"] = "additional",
        ["Eigene"] = "custom",
        ["Befehl"] = "command",
        ["Befehle"] = "commands",
        ["Nachbarn"] = "neighbors",
        ["leer"] = "empty",
        ["Strikte"] = "strict",
        ["Kompatibilität"] = "compatibility",
        ["erweitern"] = "extend",
        ["Methode"] = "method",
        ["Instanz"] = "instance",
        ["Vergleich"] = "comparison",
        ["Nummer"] = "number",
        ["Protokoll"] = "protocol",
        ["Richtung"] = "direction",
        ["Aktion"] = "action",
        ["Maske"] = "mask",
        ["Priorität"] = "priority",
        ["für"] = "for",
        ["und"] = "and",
        ["oder"] = "or",
    };
}

public sealed class LocalizedTextConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) =>
        LocalizationService.TranslateText(value?.ToString() ?? string.Empty);

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) =>
        Binding.DoNothing;
}
